strlen – fidbits C to scalar Fortran string example
strlen Interface
Izaak "Zaak" Beekman
2017-09-29
7 statements
Source File
interface
Interface with C std lib's strlen
Called By
private function strlen(str) result(res) bind(c, name='strlen')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: str
C string
Return Value integer(kind=c_size_t)
Length of string, i.e., merge(index(str,c_null_char)-1,0,index(str,c_null_char)>0)
Description
C's std lib strlen function
All Procedures
c_f_string c_str_to_fortran SpeciesName_C strlen
Call graph
c_f_string calls strlen
c_str_to_fortran calls c_f_string
main calls c_f_string, c_str_to_fortran