c_f_string – fidbits C to scalar Fortran string example
c_f_string Subroutine
Izaak "Zaak" Beekman
2017-09-29
16 statements
Source File
public subroutine c_f_string(c_str, f_str)
Uses:
ISO_C_BINDING
Recast a C string as a Fortran scalar character pointer
Warning
f_str will become a dangling pointer if the thing pointed at by c_str becomes undefined, USE WITH CAUTION!
Warning
f_str must be of type c_char. Client code should declare the actual argument corresponding to f_str as character(kind=c_char,len=:), pointer and then perform type conversion native character() kind via assignment.
Note
This solution was inspired by @ianh's post on the Intel Fortran compiler forum at https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/392505
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: c_str
C char string to convert to a scalar Fortran string
character(kind=c_char,len=:), intent(out), pointer :: f_str
Scalar character pointer of type c_char corresponding to c_str
Calls
Called By
Variables
char_array
Subroutines
char_array_to_scalar_ptr
Variables
Type Visibility Attributes Name Initial
character(kind=c_char), public, pointer :: char_array(:)
Temp array of length 1 characters
Subroutines
subroutine char_array_to_scalar_ptr(scalar_len, scalar, ptr)
Author
Izaak "Zaak" Beekman
Date
2017-09-29
Internal procedure to recast pointer to array of length 1 characters as pointer scalar character variable of length >= 1
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: scalar_len
Length of character pointer being passed in
character(kind=c_char,len=scalar_len), intent(in), target :: scalar(1)
Temporary rank 1, size() = 1 pointer to character of len=scalar_len
character(kind=c_char,len=:), intent(out), pointer :: ptr
Scalar return pointer to persist casting as scalar character
All Procedures
c_f_string c_str_to_fortran SpeciesName_C strlen
Call graph
c_f_string calls strlen, char_array_to_scalar_ptr
c_str_to_fortran calls c_f_string
main calls c_f_string, c_str_to_fortran