c_str_to_fortran – fidbits C to scalar Fortran string example
c_str_to_fortran Function
Izaak "Zaak" Beekman
2017-09-29
8 statements
Source File
public function c_str_to_fortran(c_str) result(res)
Uses:
ISO_C_BINDING
Return a Fortran scalar string corresponding to a C string using c_f_string and then casting it as a non-pointer
Note
This will probably cause a temporary variable to be allocated
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: c_str
C string to be converted
Return Value character(len=:), allocatable
Function return, a native Fortran, scalar character variable
Calls
Called By
Variables
f_ptr_str
Variables
Type Visibility Attributes Name Initial
character(kind=c_char,len=:), public, pointer :: f_ptr_str
Temporary variable to point to C string as a native Fortran pointer
All Procedures
c_f_string c_str_to_fortran SpeciesName_C strlen
Call graph
c_str_to_fortran calls c_f_string
c_f_string calls strlen, char_array_to_scalar_ptr
main calls c_str_to_fortran