main – fidbits C to scalar Fortran string example
main Program
Izaak "Zaak" Beekman
2017-09-29
25 statements
Source File
Uses:
c_f_string_m
ISO_FORTRAN_ENV
ISO_C_BINDING
Example program to show the usage of c_f_string and c_str_to_fortran Correct output looks like:
./example SpeciesName_C(1): N SpeciesName_C(1): N SpeciesName_C(2): N2 SpeciesName_C(2): N2 SpeciesName_C(3): NO SpeciesName_C(3): NO SpeciesName_C(4): NO2 SpeciesName_C(4): NO2 SpeciesName_C(5): O SpeciesName_C(5): O SpeciesName_C(6): O2 SpeciesName_C(6): O2 SpeciesName_C(7): O3 SpeciesName_C(7): O3
Calls
Variables
n_elem
Interfaces
SpeciesName_C
Variables
Type Attributes Name Initial
integer, parameter :: n_elem = 7
Interfaces
interface
Interface with SpeciesName from str_array.c
function SpeciesName_C(idx) result(res) bind(c, name='SpeciesName')
Author
Izaak "Zaak" Beekman
Date
2017-09-29
Interface for function SpeciesName declared in str_array.c
Arguments
Type Intent Optional Attributes Name
integer(kind=c_size_t), intent(in), value :: idx
Index of const char* array to retrieve
Return Value type(c_ptr)
Returned string
All Programs
main
Call graph
main calls c_str_to_fortran, speciesname_c, c_f_string
c_str_to_fortran calls c_f_string
c_f_string calls strlen, char_array_to_scalar_ptr